# Define the global Conda environment
conda: "conda-poirot-3.10"

SUBS = ['S001', 'S002', 'S003', 'S004', 'S005', 'S006', 'S007', 
        'S008', 'S009', 'S010', 'S011', 'S012', 'S013', 'S014', 'S015']

DATA_FOLDER = "/Volumes/ExtremePro/Analyses/ASP0"
TIMESERIES_FOLDER = f"{DATA_FOLDER}/interim/timeseries"
POWER_FOLDER = f"{DATA_FOLDER}/interim/power"
MATLAB_SCRIPT = "scripts/rs/01_process_matlab_data.py"
SPECTRUM_SCRIPT = "scripts/rs/02_compute_spectrum.py"

CONFIG_FILE = "config/specparam_config.json"  # path to the configuration file


# Start the rules

rule all:
    input:
        expand(f"{POWER_FOLDER}/{{sub}}_MEG_ASSR_power.nc", sub=SUBS)

rule process_matlab_data:
    output:
        out_file = f"{TIMESERIES_FOLDER}/{{sub}}_MEG_ASSR_times.nc"
    params:
        sub = "{sub}",
        datafolder = DATA_FOLDER,
        script = MATLAB_SCRIPT
    shell:
        "python {params.script} -s {params.sub} -d {params.datafolder} -o {output.out_file}"

rule compute_spectrum_resting_state:
    input:
        in_file = rules.process_matlab_data.output.out_file
    output:
        out_file = f"{POWER_FOLDER}/{{sub}}_MEG_ASSR_power.nc"
    params:
        sub = "{sub}",
        script = SPECTRUM_SCRIPT,
        config_file = CONFIG_FILE  # pass the configuration file to the script
    shell:
        "python {params.script} -i {input.in_file} -o {output.out_file} --config {params.config_file}"

# rule copy_brainstorm_files:
#     shell:
#         'matlab -nodisplay -nosplash -nodesktop -r \"addpath(genpath('matlab/')); GPscriptRestingState; exit"'